services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
