# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

# env:

# vars:

includes:
  uc:
    taskfile: ./taskfiles/uc.yml
    aliases: ["uncloud"]
  uv:
    taskfile: ./taskfiles/uv.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  debug:
    cmds:
      - echo "Debugging information:"
      - |
        echo "    CLI_ARGS: {{.CLI_ARGS}}"
        echo "    HOME: {{.HOME}}"
        echo "    TASKFILE_DIR: {{.ROOT_DIR}}"
        echo "    GITHUB_TOKEN: {{.GITHUB_TOKEN}}"
        echo "    REDDIT_APP_NAME: {{.REDDIT_APP_NAME}}"
        echo "    REDDIT_APP_CLIENT_ID: {{.REDDIT_APP_CLIENT_ID}}"
        echo "    REDDIT_APP_SECRET: {{.REDDIT_APP_SECRET}}"
        echo "    MY_SECRET_TOKEN: {{.MY_SECRET_TOKEN}}"
        echo "    WORKING_DIR: {{.WORKING_DIR}}"
    silent: true

  deploy:
    desc: "Deploy glance"
    cmds:
      - ansible-playbook deploy.yml -vvv

  install-devbox:
    desc: "Install devbox"
    cmds:
      - curl -fsSL https://get.jetify.com/devbox | bash
    run: once
    silent: true
    environment:
      FORCE: 1
      INSTALL_DIR: "{{.HOME}}/.local/bin"
    status:
      - command -v devbox 2>/dev/null
