- type: rss
  limit: 15
  collapse-after: 5
  cache: 12h
  feeds:
    - url: https://rss.app/feeds/hduqjWEyujKjSLFU.xml
      title: Inverse
    - url: https://selfh.st/rss/
      title: selfh.st
    - url: https://rss.app/feeds/bfMDGp1eFuIYj0SJ.xml
      title: Time Extension
    - url: https://www.theverge.com/rss/partner/subscriber-only-full-feed/rss.xml
      title: The Verge
    - url: https://electrek.co/feed
      title: Electrek
    - url: https://www.pcmag.com/feeds/rss/latest
      title: PC Magagzine
    - url: https://www.wired.com/feed/rss
      title: Wired
    - url: https://www.theatlantic.com/feed/all/
      title: The Atlantic
    - url: https://www.vox.com/rss/index.xml
      title: Vox
    - url: https://rss.app/feeds/OqcaWF1AZo4RmPyB.xml
      title: AP - US News
    - url: https://rss.app/feeds/yPesgfLNjy2GRjxc.xml
      title: AP - Politics
